### ISSUE TITLE
pydocstyle

### ISSUE THREAD

**Issue by The-Compiler** [Robpol86/flake8-pydocstyle#6]
pep257 got renamed to pydocstyle: https://github.com/PyCQA/pydocstyle/issues/172 https://github.com/PyCQA/pydocstyle/pull/173

I think this tool should be updated to depend on that instead of pep257, and probably be renamed as well.

**Comment by Robpol86** [comment]
Done.

Renamed GitHub repo and renamed pep257 references in the code to pydocstyle:

https://github.com/Robpol86/flake8-pydocstyle/commit/53b9b46800ee21be0e73743eded5fc302a820e14
