### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by glennmatthews** [Robpol86/flake8-pydocstyle#8]
Is this package obsoleted by `flake8-docstrings` (https://pypi.python.org/pypi/flake8-docstrings), given that that package appears to be maintained by the developers of flake8/pycodestyle/pydocstyle?

**Comment by Robpol86** [comment]
When I wrote this I came across flake8-docstrings but unfortunately its linters were very simple and I was unsatisfied with it. Does it catch everything pep257 does? I'll have to look into it again to give you a proper reply.

**Comment by glennmatthews** [comment]
flake8-docstrings is a wrapper around pydocstyle (formerly pep257) just like flake8-pep257 - but I haven't done a side-by-side comparison of how cleanly each one integrates with flake8.

**Comment by Robpol86** [comment]
Looks like you're right. Seems like up until 8 months ago it was abandoned. I think I made this because at the time flake8-docstrings didn't support/pass ignore options from tox.ini

Now that it's being maintained I'll go ahead and obsolete this one. Thanks for bringing this to my attention.

**Comment by glennmatthews** [comment]
Thanks for confirming. This project was very useful to me in the meantime while flake8-docstrings wasn't being maintained - thanks again!
